tw-eureka-host: 172.18.0.21
tw-eureka-port: 8091
tw-gateway-host: 172.18.0.22
tw-gateway-port: 8092

server:
  port: 8094

eureka:
  instance:
    hostname: ${tw-eureka-host}
    port: ${tw-eureka-port}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
  
security:
  oauth2:
    resource:
      userInfoUri: http://${tw-gateway-host}:${tw-gateway-port}/oauth/user
      id: backend
      
spring:
  datasource:
    url:  jdbc:h2:file:~/h2/twclidb-v2;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: h2
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        event:
          merge:
            entity_copy_observer: allow
  h2:
    console:
      settings:
        trace: true
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
